brand:
  name: Codehero
  facebook: codeheroblog
  twitter: codeheroblog
  gplus: +CodeheroCo
  github: codeheroco
  linkedin: Codehero-5108125
  email: heroes@codehero.co

  disqus:
    shortname: codeheroblog

  analytics:
    google: 'UA-41464412-1'

timezone: America/Caracas
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'config.rb', 'Rakefile']
future: false

permalink: /:title
paginate_path: 'page:num'
paginate: 10

markdown: redcarpet
pygments: true
redcarpet:
  extensions: ["tables"]

safe: false
host: 0.0.0.0
port: 3000
baseurl: /

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
